---

- hosts: linux

  vars_files:
    - ./vars/logos.yaml

  tasks:

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      notify: Check HTTP Request

    - name: Install Unzip Package
      package:
        name: unzip
        state: latest

    - name: Unarchive Playbook Stacker Game
      unarchive:
        src: ./files/playbook_stacker.zip
        dest: "{{nginx_root_location}}"
        mode: 0755
        remote_src: false

    - name: Template index.html-ester_egg.j2 to index.html on target
      template:
        src: ./templates/index.html-easter_egg.j2
        dest: "{{hostvars[ansible_hostname].nginx_root_location}}/index.html"
        mode: 0644

  handlers:
    - name: Check HTTP Request
      uri:
        url: http://{{ansible_default_ipv4.address}}
        status_code:
          - 200

...