---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Using the AWS Security Group inbound rules to open ports
      ec2_group:
        name: ansible
        description: creating an ansible security group in here 
        region: ap-south-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

...