# tasks file for webapp

- name: Including the template into the target_dir
  template:
    src: index.html-easter_egg.j2
    dest: "{{target_dir}}/index.html"
    mode: 0644
  tags:
  - deploy-app

- name: install unzip package
  package:
    name: unzip
    state: latest

- name: Unarchieving the zip using the unarchive module
  unarchive:
    src: playbook_stacker.zip
    dest: "{{target_dir}}"
    mode: 0755
  tags:
  - deploy-app
